spring:
  jackson:
    serialization: 
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    #url: jdbc:mysql://localhost:3306/hcd
    #username: root
    #password: A16gosto
    url: jdbc:sqlserver://localhost:1433;databaseName=hcd
    username: sa
    password: root
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
com.st.hcd.security.jwt:
  tokenExpirationTime: 480  # Number of minutes
  refreshTokenExpTime: 1440 # Minutes
  tokenIssuer: http://stacktrace.com.ar
  
